### ISSUE TITLE
Support Map and Set

### ISSUE THREAD

**Issue by christophehurpeau** [Raynos/for-each#6]
Could you add support for Map and Set, in nodejs since 0.12 and in iojs ?
Even more, support for Iterator (if [Symbol.iterator] exists ?) ?

**Comment by ljharb** [comment]
`Map` and `Set` have `forEach` built in in 100% of their implementations - why would you need to use this module for it?

Similarly, any engine that supports `Symbol.iterator` will support `for..of`, and many of those will also support `Array.from`.

**Comment by christophehurpeau** [comment]
To be able to iterate no matter what the argument is ? But I understand your point of view :)

**Comment by ljharb** [comment]
I think the challenge is that either for-each would have to be able to identify a Map or a Set - which is not a trivial matter (instanceof lies) - or, have generic iterable support, which is not a trivial amount of code to add.

I think that this library is best kept to its current small set of use cases, so I'm going to close this.

**Comment by ljharb** [comment]
@christophehurpeau https://www.npmjs.com/package/iterate-value may be the library you're looking for :-)
